{{
  config(
    materialized = 'view',
    schema = 'gold_layer'
    )
}}

WITH TIMBGIORNO AS (
    SELECT
        AU.USER_ID                        AS ADDETTO,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE) AS GIORNOTIMBRATURA,
        SUM(LL.TOTALTIME_QTY) / 60        AS TOTPRESENZAMINUTI
    FROM
        {{ ref('loglavorazione_incremental') }} AS LL
    INNER JOIN {{ ref('users_incremental') }} AS AU
        ON LL.USERPK_CODE = AU.PK
    WHERE
        LL.STATUS_TYPE = "COMPLETED"
        AND AU.USER_ID IS NOT NULL
    GROUP BY
        AU.USER_ID,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE)
),

LAVGIORNO AS (
    SELECT
        AU.USER_ID                        AS ADDETTO,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE) AS GIORNO,
        TIMESTAMP_DIFF(
            TIMESTAMP_TRUNC(MAX(LL.ENDDATE_TSTAMP), MINUTE),
            TIMESTAMP_TRUNC(MIN(LL.STARTDATE_TSTAMP), MINUTE),
            MINUTE
        )                                 AS TOTLAVORAZIONEMINUTI
    FROM {{ ref('loglavorazione_incremental') }} AS LL
    INNER JOIN {{ ref('users_incremental') }} AS AU
        ON LL.USERPK_CODE = AU.PK
    WHERE
        LL.STATUS_TYPE = "COMPLETED"
        AND AU.USER_ID IS NOT NULL
    GROUP BY
        AU.USER_ID,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE)
),

PAUSE AS (
    SELECT
        AU.USER_ID                       AS ADDETTO,
        P.USERPK_CODE,
        P.TYPE_NAME,
        CAST(P.STARTDATE_TSTAMP AS DATE) AS GIORNO,
        SUM(TIMESTAMP_DIFF(P.ENDDATE_TSTAMP, P.STARTDATE_TSTAMP, MINUTE))
        - ABS(
            TIMESTAMP_DIFF(P.ENDDATE_TSTAMP, P.STARTDATE_TSTAMP, MINUTE)
            - SUM(TIMESTAMP_DIFF(P.ENDDATE_TSTAMP, P.STARTDATE_TSTAMP, MINUTE))
        )                                AS PAUSAMINUTI
    FROM {{ ref('interruzioni_incremental') }} AS P
    INNER JOIN {{ ref('users_incremental') }} AS AU
        ON P.USERPK_CODE = AU.PK
    WHERE
        P.TYPE_NAME IN ("ORDINARIA", "Pausa Ordinaria")
        AND AU.USER_ID IS NOT NULL
    GROUP BY
        AU.USER_ID,
        P.USERPK_CODE,
        CAST(P.STARTDATE_TSTAMP AS DATE),
        P.STARTDATE_TSTAMP,
        P.ENDDATE_TSTAMP,
        P.TYPE_NAME
),

ECOPUREGIORNO AS (
    SELECT
        AU.USER_ID                        AS ADDETTO,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE) AS GIORNO,
        SUM(LL.ACTUALTIME_QTY) / 60.0     AS ECOPUREMINUTI
    FROM {{ ref('loglavorazione_incremental') }} AS LL
    INNER JOIN {{ ref('users_incremental') }} AS AU
        ON LL.USERPK_CODE = AU.PK
    WHERE
        LL.STATUS_TYPE = "COMPLETED"
        AND LL.CODICEMOTIVOECONOMIA_CODE IS NOT NULL
        AND AU.USER_ID IS NOT NULL
    GROUP BY
        AU.USER_ID,
        LL.USERPK_CODE,
        CAST(LL.STARTDATE_TSTAMP AS DATE)
),

LAVWINDOW AS (
    SELECT
        TG.ADDETTO,
        TG.GIORNOTIMBRATURA,
        TG.TOTPRESENZAMINUTI,
        LG.TOTLAVORAZIONEMINUTI,
        SUM(COALESCE(P.PAUSAMINUTI, 0.0))
            OVER (PARTITION BY TG.USERPK_CODE, TG.GIORNOTIMBRATURA)
            AS TOTPAUSAMINUTI,
        SUM(COALESCE(EPG.ECOPUREMINUTI, 0.0))
            OVER (PARTITION BY TG.USERPK_CODE, TG.GIORNOTIMBRATURA)
            AS TOTECOPUREMINUTI
    FROM TIMBGIORNO AS TG
    INNER JOIN LAVGIORNO AS LG
        ON
            TG.USERPK_CODE = LG.USERPK_CODE
            AND TG.GIORNOTIMBRATURA = LG.GIORNO
    LEFT JOIN PAUSE AS P
        ON
            LG.USERPK_CODE = P.USERPK_CODE
            AND LG.GIORNO = P.GIORNO
    LEFT JOIN ECOPUREGIORNO AS EPG
        ON
            LG.USERPK_CODE = EPG.USERPK_CODE
            AND LG.GIORNO = EPG.GIORNO
)

SELECT
    "TEMERA"                AS SOURCE_,
    LW.ADDETTO              AS ADDETTO_CODE,
    LW.GIORNOTIMBRATURA     AS DATA_,
    LW.TOTPRESENZAMINUTI    AS MINUTI_PRESENZA_QTY,
    LW.TOTLAVORAZIONEMINUTI AS MINUTI_LAVORATI_QTY,
    LW.TOTPAUSAMINUTI       AS MINUTI_PAUSA_QTY,
    LW.TOTECOPUREMINUTI     AS MINUTI_ECOPURE_QTY
FROM LAVWINDOW AS LW
